# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

include: ['_pages']

title: Disencyclopedia
baseurl: /
url: https://desinfo.quaidorsay.fr

remote_theme: ambanum/just-the-docs
search_enabled: true

defaults:
  -
    scope:
      path: "" # means "all files"
    values:
      layout: page

exclude:
  - README.md
  - .circleci
  - vendor
